#include <offer/protocol/get_config.hpp>
#include <offer/protocol/config.hpp>
#include <offer/protocol/asset.hpp>
#include <offer/protocol/types.hpp>
#include <offer/protocol/version.hpp>

namespace offer { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
#ifdef OFFER_ENABLE_SMT
   result[ "OFFER_ENABLE_SMT" ] = true;
   result["SMT_COINING_WITHDRAW_INTERVAL_SECONDS"] = SMT_COINING_WITHDRAW_INTERVAL_SECONDS;
   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
#else
   result[ "OFFER_ENABLE_SMT" ] = false;
#endif

   result["BSD_SYMBOL"] = BSD_SYMBOL;
   result["OFFER_INITIAL_VOTE_POWER_RATE"] = OFFER_INITIAL_VOTE_POWER_RATE;
   result["OFFER_REDUCED_VOTE_POWER_RATE"] = OFFER_REDUCED_VOTE_POWER_RATE;
   result["OFFER_100_PERCENT"] = OFFER_100_PERCENT;
   result["OFFER_1_PERCENT"] = OFFER_1_PERCENT;
   result["OFFER_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = OFFER_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["OFFER_ACTIVE_CHALLENGE_COOLDOWN"] = OFFER_ACTIVE_CHALLENGE_COOLDOWN;
   result["OFFER_ACTIVE_CHALLENGE_FEE"] = OFFER_ACTIVE_CHALLENGE_FEE;
   result["OFFER_ADDRESS_PREFIX"] = OFFER_ADDRESS_PREFIX;
   result["OFFER_APR_PERCENT_MULTIPLY_PER_BLOCK"] = OFFER_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["OFFER_APR_PERCENT_MULTIPLY_PER_HOUR"] = OFFER_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["OFFER_APR_PERCENT_MULTIPLY_PER_ROUND"] = OFFER_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["OFFER_APR_PERCENT_SHIFT_PER_BLOCK"] = OFFER_APR_PERCENT_SHIFT_PER_BLOCK;
   result["OFFER_APR_PERCENT_SHIFT_PER_HOUR"] = OFFER_APR_PERCENT_SHIFT_PER_HOUR;
   result["OFFER_APR_PERCENT_SHIFT_PER_ROUND"] = OFFER_APR_PERCENT_SHIFT_PER_ROUND;
   result["OFFER_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = OFFER_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["OFFER_BANDWIDTH_PRECISION"] = OFFER_BANDWIDTH_PRECISION;
   result["OFFER_BLOCKCHAIN_PRECISION"] = OFFER_BLOCKCHAIN_PRECISION;
   result["OFFER_BLOCKCHAIN_PRECISION_DIGITS"] = OFFER_BLOCKCHAIN_PRECISION_DIGITS;
   result["OFFER_BLOCKCHAIN_HARDFORK_VERSION"] = OFFER_BLOCKCHAIN_HARDFORK_VERSION;
   result["OFFER_BLOCKCHAIN_VERSION"] = OFFER_BLOCKCHAIN_VERSION;
   result["OFFER_BLOCK_INTERVAL"] = OFFER_BLOCK_INTERVAL;
   result["OFFER_BLOCKS_PER_DAY"] = OFFER_BLOCKS_PER_DAY;
   result["OFFER_BLOCKS_PER_HOUR"] = OFFER_BLOCKS_PER_HOUR;
   result["OFFER_BLOCKS_PER_YEAR"] = OFFER_BLOCKS_PER_YEAR;
   result["OFFER_CASHOUT_WINDOW_SECONDS"] = OFFER_CASHOUT_WINDOW_SECONDS;
   result["OFFER_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = OFFER_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["OFFER_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = OFFER_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["OFFER_CHAIN_ID"] = OFFER_CHAIN_ID;
   result["OFFER_COMMENT_REWARD_FUND_NAME"] = OFFER_COMMENT_REWARD_FUND_NAME;
   result["OFFER_CONTENT_APR_PERCENT"] = OFFER_CONTENT_APR_PERCENT;
   result["OFFER_CONTENT_CONSTANT_HF0"] = OFFER_CONTENT_CONSTANT_HF0;
   result["OFFER_CONTENT_REWARD_PERCENT"] = OFFER_CONTENT_REWARD_PERCENT;
   result["OFFER_CONVERSION_DELAY"] = OFFER_CONVERSION_DELAY;
   result["OFFER_CONVERSION_DELAY_PRE_HF_16"] = OFFER_CONVERSION_DELAY_PRE_HF_16;
   result["OFFER_CREATE_ACCOUNT_DELEGATION_RATIO"] = OFFER_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["OFFER_CREATE_ACCOUNT_DELEGATION_TIME"] = OFFER_CREATE_ACCOUNT_DELEGATION_TIME;
   result["OFFER_CREATE_ACCOUNT_WITH_OFFER_MODIFIER"] = OFFER_CREATE_ACCOUNT_WITH_OFFER_MODIFIER;
   result["OFFER_CURATE_APR_PERCENT"] = OFFER_CURATE_APR_PERCENT;
   result["OFFER_DEFAULT_BSD_INTEREST_RATE"] = OFFER_DEFAULT_BSD_INTEREST_RATE;
   result["OFFER_EQUIHASH_K"] = OFFER_EQUIHASH_K;
   result["OFFER_EQUIHASH_N"] = OFFER_EQUIHASH_N;
   result["OFFER_FEED_HISTORY_WINDOW"] = OFFER_FEED_HISTORY_WINDOW;
   result["OFFER_FEED_HISTORY_WINDOW_PRE_HF_16"] = OFFER_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["OFFER_FEED_INTERVAL_BLOCKS"] = OFFER_FEED_INTERVAL_BLOCKS;
   result["OFFER_GENESIS_TIME"] = OFFER_GENESIS_TIME;
   result["OFFER_HARDFORK_REQUIRED_WITNESSES"] = OFFER_HARDFORK_REQUIRED_WITNESSES;
   result["OFFER_INFLATION_NARROWING_PERIOD"] = OFFER_INFLATION_NARROWING_PERIOD;
   result["OFFER_INFLATION_RATE_START_PERCENT"] = OFFER_INFLATION_RATE_START_PERCENT;
   result["OFFER_INFLATION_RATE_STOP_PERCENT"] = OFFER_INFLATION_RATE_STOP_PERCENT;
   result["OFFER_INIT_MINER_NAME"] = OFFER_INIT_MINER_NAME;
   result["OFFER_INIT_PUBLIC_KEY_STR"] = OFFER_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["OFFER_INIT_PRIVATE_KEY"] = OFFER_INIT_PRIVATE_KEY;
#endif
   result["OFFER_INIT_SUPPLY"] = OFFER_INIT_SUPPLY;
   result["OFFER_INIT_TIME"] = OFFER_INIT_TIME;
   result["OFFER_IRREVERSIBLE_THRESHOLD"] = OFFER_IRREVERSIBLE_THRESHOLD;
   result["OFFER_LIQUIDITY_APR_PERCENT"] = OFFER_LIQUIDITY_APR_PERCENT;
   result["OFFER_LIQUIDITY_REWARD_BLOCKS"] = OFFER_LIQUIDITY_REWARD_BLOCKS;
   result["OFFER_LIQUIDITY_REWARD_PERIOD_SEC"] = OFFER_LIQUIDITY_REWARD_PERIOD_SEC;
   result["OFFER_LIQUIDITY_TIMEOUT_SEC"] = OFFER_LIQUIDITY_TIMEOUT_SEC;
   result["OFFER_MAX_ACCOUNT_CREATION_FEE"] = OFFER_MAX_ACCOUNT_CREATION_FEE;
   result["OFFER_MAX_ACCOUNT_NAME_LENGTH"] = OFFER_MAX_ACCOUNT_NAME_LENGTH;
   result["OFFER_MAX_ACCOUNT_WITNESS_VOTES"] = OFFER_MAX_ACCOUNT_WITNESS_VOTES;
   result["OFFER_MAX_ASSET_WHITELIST_AUTHORITIES"] = OFFER_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["OFFER_MAX_AUTHORITY_MEMBERSHIP"] = OFFER_MAX_AUTHORITY_MEMBERSHIP;
   result["OFFER_MAX_BLOCK_SIZE"] = OFFER_MAX_BLOCK_SIZE;
   result["OFFER_SOFT_MAX_BLOCK_SIZE"] = OFFER_SOFT_MAX_BLOCK_SIZE;
   result["OFFER_MAX_CASHOUT_WINDOW_SECONDS"] = OFFER_MAX_CASHOUT_WINDOW_SECONDS;
   result["OFFER_MAX_COMMENT_DEPTH"] = OFFER_MAX_COMMENT_DEPTH;
   result["OFFER_MAX_COMMENT_DEPTH_PRE_HF17"] = OFFER_MAX_COMMENT_DEPTH_PRE_HF17;
   result["OFFER_MAX_FEED_AGE_SECONDS"] = OFFER_MAX_FEED_AGE_SECONDS;
   result["OFFER_MAX_INSTANCE_ID"] = OFFER_MAX_INSTANCE_ID;
   result["OFFER_MAX_MEMO_SIZE"] = OFFER_MAX_MEMO_SIZE;
   result["OFFER_MAX_WITNESSES"] = OFFER_MAX_WITNESSES;
   result["OFFER_MAX_MINER_WITNESSES_HF0"] = OFFER_MAX_MINER_WITNESSES_HF0;
   result["OFFER_MAX_MINER_WITNESSES_HF17"] = OFFER_MAX_MINER_WITNESSES_HF17;
   result["OFFER_MAX_PERMLINK_LENGTH"] = OFFER_MAX_PERMLINK_LENGTH;
   result["OFFER_MAX_PROXY_RECURSION_DEPTH"] = OFFER_MAX_PROXY_RECURSION_DEPTH;
   result["OFFER_MAX_RATION_DECAY_RATE"] = OFFER_MAX_RATION_DECAY_RATE;
   result["OFFER_MAX_RESERVE_RATIO"] = OFFER_MAX_RESERVE_RATIO;
   result["OFFER_MAX_RUNNER_WITNESSES_HF0"] = OFFER_MAX_RUNNER_WITNESSES_HF0;
   result["OFFER_MAX_RUNNER_WITNESSES_HF17"] = OFFER_MAX_RUNNER_WITNESSES_HF17;
   result["OFFER_MAX_SATOSHIS"] = OFFER_MAX_SATOSHIS;
   result["OFFER_MAX_SHARE_SUPPLY"] = OFFER_MAX_SHARE_SUPPLY;
   result["OFFER_MAX_SIG_CHECK_DEPTH"] = OFFER_MAX_SIG_CHECK_DEPTH;
   result["OFFER_MAX_SIG_CHECK_ACCOUNTS"] = OFFER_MAX_SIG_CHECK_ACCOUNTS;
   result["OFFER_MAX_TIME_UNTIL_EXPIRATION"] = OFFER_MAX_TIME_UNTIL_EXPIRATION;
   result["OFFER_MAX_TRANSACTION_SIZE"] = OFFER_MAX_TRANSACTION_SIZE;
   result["OFFER_MAX_UNDO_HISTORY"] = OFFER_MAX_UNDO_HISTORY;
   result["OFFER_MAX_URL_LENGTH"] = OFFER_MAX_URL_LENGTH;
   result["OFFER_MAX_VOTE_CHANGES"] = OFFER_MAX_VOTE_CHANGES;
   result["OFFER_MAX_VOTED_WITNESSES_HF0"] = OFFER_MAX_VOTED_WITNESSES_HF0;
   result["OFFER_MAX_VOTED_WITNESSES_HF17"] = OFFER_MAX_VOTED_WITNESSES_HF17;
   result["OFFER_MAX_WITHDRAW_ROUTES"] = OFFER_MAX_WITHDRAW_ROUTES;
   result["OFFER_MAX_WITNESS_URL_LENGTH"] = OFFER_MAX_WITNESS_URL_LENGTH;
   result["OFFER_MIN_ACCOUNT_CREATION_FEE"] = OFFER_MIN_ACCOUNT_CREATION_FEE;
   result["OFFER_MIN_ACCOUNT_NAME_LENGTH"] = OFFER_MIN_ACCOUNT_NAME_LENGTH;
   result["OFFER_MIN_BLOCK_SIZE_LIMIT"] = OFFER_MIN_BLOCK_SIZE_LIMIT;
   result["OFFER_MIN_BLOCK_SIZE"] = OFFER_MIN_BLOCK_SIZE;
   result["OFFER_MIN_CONTENT_REWARD"] = OFFER_MIN_CONTENT_REWARD;
   result["OFFER_MIN_CURATE_REWARD"] = OFFER_MIN_CURATE_REWARD;
   result["OFFER_MIN_PERMLINK_LENGTH"] = OFFER_MIN_PERMLINK_LENGTH;
   result["OFFER_MIN_REPLY_INTERVAL"] = OFFER_MIN_REPLY_INTERVAL;
   result["OFFER_MIN_REPLY_INTERVAL_HF20"] = OFFER_MIN_REPLY_INTERVAL_HF20;
   result["OFFER_MIN_ROOT_COMMENT_INTERVAL"] = OFFER_MIN_ROOT_COMMENT_INTERVAL;
   result["OFFER_MIN_VOTE_INTERVAL_SEC"] = OFFER_MIN_VOTE_INTERVAL_SEC;
   result["OFFER_MINER_ACCOUNT"] = OFFER_MINER_ACCOUNT;
   result["OFFER_MINER_PAY_PERCENT"] = OFFER_MINER_PAY_PERCENT;
   result["OFFER_MIN_FEEDS"] = OFFER_MIN_FEEDS;
   result["OFFER_MINING_REWARD"] = OFFER_MINING_REWARD;
   result["OFFER_MINING_TIME"] = OFFER_MINING_TIME;
   result["OFFER_MIN_LIQUIDITY_REWARD"] = OFFER_MIN_LIQUIDITY_REWARD;
   result["OFFER_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = OFFER_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["OFFER_MIN_PAYOUT_BSD"] = OFFER_MIN_PAYOUT_BSD;
   result["OFFER_MIN_POW_REWARD"] = OFFER_MIN_POW_REWARD;
   result["OFFER_MIN_PRODUCER_REWARD"] = OFFER_MIN_PRODUCER_REWARD;
   result["OFFER_MIN_TRANSACTION_EXPIRATION_LIMIT"] = OFFER_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["OFFER_MIN_TRANSACTION_SIZE_LIMIT"] = OFFER_MIN_TRANSACTION_SIZE_LIMIT;
   result["OFFER_MIN_UNDO_HISTORY"] = OFFER_MIN_UNDO_HISTORY;
   result["OFFER_NULL_ACCOUNT"] = OFFER_NULL_ACCOUNT;
   result["OFFER_NUM_INIT_MINERS"] = OFFER_NUM_INIT_MINERS;
   result["OFFER_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = OFFER_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["OFFER_OWNER_AUTH_RECOVERY_PERIOD"] = OFFER_OWNER_AUTH_RECOVERY_PERIOD;
   result["OFFER_OWNER_CHALLENGE_COOLDOWN"] = OFFER_OWNER_CHALLENGE_COOLDOWN;
   result["OFFER_OWNER_CHALLENGE_FEE"] = OFFER_OWNER_CHALLENGE_FEE;
   result["OFFER_OWNER_UPDATE_LIMIT"] = OFFER_OWNER_UPDATE_LIMIT;
   result["OFFER_POST_AVERAGE_WINDOW"] = OFFER_POST_AVERAGE_WINDOW;
   result["OFFER_POST_REWARD_FUND_NAME"] = OFFER_POST_REWARD_FUND_NAME;
   result["OFFER_POST_WEIGHT_CONSTANT"] = OFFER_POST_WEIGHT_CONSTANT;
   result["OFFER_POW_APR_PERCENT"] = OFFER_POW_APR_PERCENT;
   result["OFFER_PRODUCER_APR_PERCENT"] = OFFER_PRODUCER_APR_PERCENT;
   result["OFFER_PROXY_TO_SELF_ACCOUNT"] = OFFER_PROXY_TO_SELF_ACCOUNT;
   result["OFFER_BSD_INTEREST_COMPOUND_INTERVAL_SEC"] = OFFER_BSD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["OFFER_SECONDS_PER_YEAR"] = OFFER_SECONDS_PER_YEAR;
   result["OFFER_RECENT_RSHARES_DECAY_TIME_HF19"] = OFFER_RECENT_RSHARES_DECAY_TIME_HF19;
   result["OFFER_RECENT_RSHARES_DECAY_TIME_HF17"] = OFFER_RECENT_RSHARES_DECAY_TIME_HF17;
   result["OFFER_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = OFFER_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["OFFER_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = OFFER_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["OFFER_ROOT_POST_PARENT"] = OFFER_ROOT_POST_PARENT;
   result["OFFER_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = OFFER_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["OFFER_SAVINGS_WITHDRAW_TIME"] = OFFER_SAVINGS_WITHDRAW_TIME;
   result["OFFER_BSD_START_PERCENT_HF14"] = OFFER_BSD_START_PERCENT_HF14;
   result["OFFER_BSD_START_PERCENT_HF20"] = OFFER_BSD_START_PERCENT_HF20;
   result["OFFER_BSD_STOP_PERCENT_HF14"] = OFFER_BSD_STOP_PERCENT_HF14;
   result["OFFER_BSD_STOP_PERCENT_HF20"] = OFFER_BSD_STOP_PERCENT_HF20;
   result["OFFER_SECOND_CASHOUT_WINDOW"] = OFFER_SECOND_CASHOUT_WINDOW;
   result["OFFER_SOFT_MAX_COMMENT_DEPTH"] = OFFER_SOFT_MAX_COMMENT_DEPTH;
   result["OFFER_START_MINER_VOTING_BLOCK"] = OFFER_START_MINER_VOTING_BLOCK;
   result["OFFER_START_COINING_BLOCK"] = OFFER_START_COINING_BLOCK;
   result["OFFER_TEMP_ACCOUNT"] = OFFER_TEMP_ACCOUNT;
   result["OFFER_UPVOTE_LOCKOUT_HF7"] = OFFER_UPVOTE_LOCKOUT_HF7;
   result["OFFER_UPVOTE_LOCKOUT_HF17"] = OFFER_UPVOTE_LOCKOUT_HF17;
   result["OFFER_UPVOTE_LOCKOUT_SECONDS"] = OFFER_UPVOTE_LOCKOUT_SECONDS;
   result["OFFER_COINING_FUND_PERCENT"] = OFFER_COINING_FUND_PERCENT;
   result["OFFER_COINING_WITHDRAW_INTERVALS"] = OFFER_COINING_WITHDRAW_INTERVALS;
   result["OFFER_COINING_WITHDRAW_INTERVALS_PRE_HF_16"] = OFFER_COINING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["OFFER_COINING_WITHDRAW_INTERVAL_SECONDS"] = OFFER_COINING_WITHDRAW_INTERVAL_SECONDS;
   result["OFFER_VOTE_DUST_THRESHOLD"] = OFFER_VOTE_DUST_THRESHOLD;
   result["OFFER_VOTING_MANA_REGENERATION_SECONDS"] = OFFER_VOTING_MANA_REGENERATION_SECONDS;
   result["OFFER_SYMBOL"] = OFFER_SYMBOL;
   result["COINS_SYMBOL"] = COINS_SYMBOL;
   result["OFFER_VIRTUAL_SCHEDULE_LAP_LENGTH"] = OFFER_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["OFFER_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = OFFER_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["OFFER_MAX_LIMIT_ORDER_EXPIRATION"] = OFFER_MAX_LIMIT_ORDER_EXPIRATION;
   result["OFFER_DELEGATION_RETURN_PERIOD_HF0"] = OFFER_DELEGATION_RETURN_PERIOD_HF0;
   result["OFFER_DELEGATION_RETURN_PERIOD_HF20"] = OFFER_DELEGATION_RETURN_PERIOD_HF20;
   result["OFFER_RD_MIN_DECAY_BITS"] = OFFER_RD_MIN_DECAY_BITS;
   result["OFFER_RD_MAX_DECAY_BITS"] = OFFER_RD_MAX_DECAY_BITS;
   result["OFFER_RD_DECAY_DENOM_SHIFT"] = OFFER_RD_DECAY_DENOM_SHIFT;
   result["OFFER_RD_MAX_POOL_BITS"] = OFFER_RD_MAX_POOL_BITS;
   result["OFFER_RD_MAX_BUDGET_1"] = OFFER_RD_MAX_BUDGET_1;
   result["OFFER_RD_MAX_BUDGET_2"] = OFFER_RD_MAX_BUDGET_2;
   result["OFFER_RD_MAX_BUDGET_3"] = OFFER_RD_MAX_BUDGET_3;
   result["OFFER_RD_MAX_BUDGET"] = OFFER_RD_MAX_BUDGET;
   result["OFFER_RD_MIN_DECAY"] = OFFER_RD_MIN_DECAY;
   result["OFFER_RD_MIN_BUDGET"] = OFFER_RD_MIN_BUDGET;
   result["OFFER_RD_MAX_DECAY"] = OFFER_RD_MAX_DECAY;
   result["OFFER_ACCOUNT_SUBSIDY_PRECISION"] = OFFER_ACCOUNT_SUBSIDY_PRECISION;
   result["OFFER_WITNESS_SUBSIDY_BUDGET_PERCENT"] = OFFER_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["OFFER_WITNESS_SUBSIDY_DECAY_PERCENT"] = OFFER_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["OFFER_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = OFFER_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["OFFER_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = OFFER_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["OFFER_DECAY_BACKSTOP_PERCENT"] = OFFER_DECAY_BACKSTOP_PERCENT;

   return result;
}

} } // offer::protocol
